# Generated by Django 5.1.4 on 2025-10-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.salesrepresentative'),
        ),
    ]
