# Generated by Django 5.1.4 on 2025-10-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invoice_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_sale_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_orders', to='accounts.salesrepresentative'),
        ),
    ]
