# Generated by Django 5.1.4 on 2025-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_name_PO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
