# Generated by Django 5.1.4 on 2025-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_order_order_type_order_order_name_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
