# Generated by Django 5.2.4 on 2025-08-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/defult_img.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
