# Generated by Django 5.1.4 on 2025-11-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_order_product_order_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patch_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
    ]
