# Generated by Django 5.2.4 on 2025-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Digitizing', 'Digitizing'), ('Vector', 'Vector'), ('Patch', 'Patch'), ('Quote', 'Quote')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
