# Generated by Django 5.1.4 on 2025-11-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='assigned_sale_rep',
            new_name='assigned_sale_reps',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
        ),
    ]
