# Generated by Django 5.1.4 on 2026-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_assigned_sale_rep_order_assigned_sale_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
    ]
