# Generated by Django 5.1.4 on 2026-01-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_invoice_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='date_completed',
        ),
    ]
