# Generated by Django 5.1.4 on 2025-08-06 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_admin_designer_salesrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='accounts.salesrepresentative'),
        ),
    ]
