# Generated by Django 5.1.4 on 2026-01-13 17:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_created_at_invoice_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/', validators=[accounts.models.Order.validate_2mb_file]),
        ),
    ]
