# Generated by Django 5.1.4 on 2025-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
