# Generated by Django 5.1.4 on 2025-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Company', max_length=255)),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('default_order_status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
