# Generated by Django 5.1.4 on 2025-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='designermessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
