# Generated by Django 5.1.4 on 2025-08-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_order_fabric_material_order_placement_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='Additional_information',
        ),
    ]
