# Generated by Django 5.1.4 on 2025-08-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_note_order_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Height',
            field=models.CharField(blank=True, default='standard', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Required_Format',
            field=models.CharField(blank=True, choices=[('100', '100'), ('cdr', 'cdr'), ('cdn', 'cdn'), ('dsb', 'dsb'), ('dst', 'dst'), ('dsz', 'dsz'), ('emb', 'emb'), ('exp', 'exp'), ('jef', 'jef'), ('ksm', 'ksm'), ('ofm', 'ofm'), ('pes', 'pes'), ('pxf', 'pxf'), ('pof', 'pof'), ('tap', 'tap'), ('xxx', 'xxx'), ('other', 'Other')], default='DST', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Width',
            field=models.CharField(blank=True, default='standard', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fabric_material',
            field=models.CharField(blank=True, choices=[('Blanket', 'Blanket'), ('Canvas', 'Canvas'), ('Canis', 'Canis'), ('Cotton Woven', 'Cotton Woven'), ('Denim', 'Denim'), ('Felt', 'Felt'), ('Flannel', 'Flannel'), ('Fleece', 'Fleece'), ('Leather', 'Leather'), ('Nylon', 'Nylon'), ('Pique', 'Pique'), ('Polyester', 'Polyester'), ('Silk', 'Silk'), ('Single Jersey', 'Single Jersey'), ('Towel', 'Towel'), ('Twill', 'Twill'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='placement',
            field=models.CharField(blank=True, choices=[('Apron', 'Apron'), ('Bags', 'Bags'), ('Cap', 'Cap'), ('Cap Side', 'Cap Side'), ('Cap Back', 'Cap Back'), ('Chest', 'Chest'), ('Gloves', 'Gloves'), ('Jacket Back', 'Jacket Back'), ('Patches', 'Patches'), ('Sleeve', 'Sleeve'), ('Towel', 'Towel'), ('Visor', 'Visor'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
