# Generated by Django 5.1.4 on 2025-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_order_height_order_required_format_order_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='thread_color',
        ),
        migrations.AddField(
            model_name='order',
            name='total_colors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
