# Generated by Django 5.1.4 on 2025-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
