# Generated by Django 5.1.4 on 2025-08-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_salesrepresentative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_to',
        ),
    ]
